<?php
/**
 * News template for list of customer liked news
 */

/**
 * @var $this Study_News_Block_Customer
 * @see Study_News_Block_Customer
 */
?>
<div id="liked_news_list_messages"><?php echo $this->getMessagesBlock()
        ->getGroupedHtml() ?></div>

<div>
    <h1><?php echo Mage::helper('study_news')->__('My Liked News') ?></h1>
</div>

<div>
    <?php
    if($this->getCollection()->count() > 0){
        foreach($this->getCollection() as $news){
    ?>
        <div>
            <div>
                <?php echo $news->getTitle(); ?>
            </div>
            <div>[
                <a href="<?php echo $this->getRemoveUrl($news);?>">
                    <?php echo Mage::helper('study_news')->__('REMOVE'); ?>
                </a>
                |
                <a href="<?php echo $this->getViewUrl($news);?>">
                    <?php echo Mage::helper('study_news')->__('VIEW'); ?>
                </a>
                ]</div>
        </div>
    <?php
        }
    } else {
    ?>
        <div><?php echo Mage::helper('study_news')->__('No liked News'); ?></div>
    <?php
    }
    ?>

</div>
