<?php
/**
 * Like button template for  news
 */

/**
 * @var $this Study_News_Block_Like
 * @see Study_News_Block_Like
 */
?>
<?php if(!$this->isLiked()){ ?>
<form id="likeNews" action="<?php echo $this->getLikeItUrl(); ?>" method="get" class="block">
    <div class="actions">
        <button type="submit" title="<?php echo $this->__('I Like It') ?>"
                class="button">
                <span>
                    <span><?php echo $this->__('I Like It') ?></span>
                </span>
        </button>
    </div>
</form>
<?php } ?>